const pageIndex=[
 {title:'Home',url:'index.html',text:'Andrew Holmes student developer technology coding cybersecurity IT live production.'},
 {title:'Technology FAQ',url:'faq.html',text:'Frequently asked questions about computers software hardware cybersecurity networking updates and troubleshooting.'},
 {title:'Technology Directory',url:'directory.html',text:'A collection of useful technology notes and resources organized by software hardware updates security and web development.'},
 {title:'Streams & Live Production',url:'streams.html',text:'Streams and live events Andrew has helped with using PTZ Optics cameras vMix and video production.'},
 {title:'Resume',url:'resume.html',text:'Andrew Holmes education skills experience and technology resume.'},
 {title:'Contact',url:'contact.html',text:'Contact Andrew Holmes and send a message.'}
];
const menu=document.querySelector('.menu-toggle');if(menu)menu.addEventListener('click',()=>{const links=document.querySelector('.nav-links');const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',open)});
function renderResults(query){const target=document.querySelector('#search-results');if(!target)return;const q=(query||'').trim().toLowerCase();const matches=q?pageIndex.filter(p=>(p.title+' '+p.text).toLowerCase().includes(q)):pageIndex;target.innerHTML=matches.length?matches.map(p=>`<article class="search-result"><h3><a href="${p.url}">${p.title}</a></h3><p>${p.text}</p></article>`).join(''):'<p class="empty">No pages matched that search. Try another keyword or <a href="faq.html#ask">ask a question.</a></p>';const count=document.querySelector('#search-count');if(count)count.textContent=q?`${matches.length} result${matches.length===1?'':'s'} for “${query}”`:'All site pages';}
const params=new URLSearchParams(location.search);if(document.querySelector('#search-results')){const input=document.querySelector('#site-search');input.value=params.get('q')||'';renderResults(input.value);input.addEventListener('input',()=>renderResults(input.value));document.querySelector('#search-form').addEventListener('submit',e=>{e.preventDefault();history.replaceState({},'',`search.html?q=${encodeURIComponent(input.value)}`);renderResults(input.value)})}
const filters=document.querySelectorAll('.filter');if(filters.length)filters.forEach(button=>button.addEventListener('click',()=>{filters.forEach(b=>b.classList.remove('active'));button.classList.add('active');const tag=button.dataset.tag;document.querySelectorAll('.directory-card').forEach(card=>card.hidden=tag!=='all'&&card.dataset.tag!==tag)}));
const questionForm=document.querySelector('#question-form');if(questionForm)questionForm.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(questionForm);const text=`Question submitted: ${new Date().toLocaleString()}\nName: ${data.get('name')}\nQuestion: ${data.get('question')}\n\n`;const blob=new Blob([text],{type:'text/plain'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='questions.txt';link.click();URL.revokeObjectURL(link.href);document.querySelector('#form-message').textContent='Your questions.txt file is ready to download. Please send it to Andrew so it can be answered and added to the FAQ.';questionForm.reset()});
